default_language_version:
    python: python3.11

repos:
    - repo: https://github.com/ambv/black
      rev: 23.12.0
      hooks:
          - id: black

    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v1.3.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-yaml
            args: ["--unsafe"]
          - id: debug-statements

    - repo: https://github.com/pycqa/isort
      rev: 5.13.1
      hooks:
          - id: isort
            name: isort (python)
            args: ["--settings", "pyproject.toml"]
